"""First revision

Revision ID: 71712da2af3a
Revises: 
Create Date: 2023-05-11 15:18:10.365086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71712da2af3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
